"use client";

import { useRef } from "react";
import { motion, AnimatePresence } from "framer-motion";
import { Icon } from "@iconify/react";
import { cn } from "@/lib/utils";
import {
  PropertyTransferResult,
  Currency,
  formatCurrency,
  CURRENCY_SYMBOLS,
  TranslationStrings,
  getTaxTypeName,
  getPayerLabel,
} from "@/lib/calculators/property-transfer";

// ============================================
// TYPES
// ============================================

interface PrintableReportProps {
  isOpen: boolean;
  onClose: () => void;
  result: PropertyTransferResult;
  currency: Currency;
  input: {
    purchasePrice: number;
    registeredValue: number;
    yearsOwned: number;
    sellerType: string;
    loanAmount?: number;
    applyIncentive: boolean;
  };
  t: TranslationStrings;
}

// ============================================
// TRANSLATIONS FOR REPORT
// ============================================

const reportTranslations = {
  en: {
    title: "Property Transfer Fee Report",
    subtitle: "Thailand Real Estate Transaction Cost Analysis",
    reportDate: "Report Date",
    reference: "Reference",
    propertyDetails: "Property Details",
    purchasePrice: "Purchase Price",
    registeredValue: "Registered Value",
    yearsOwned: "Years Owned",
    sellerType: "Seller Type",
    mortgage: "Mortgage Amount",
    individual: "Individual",
    company: "Company",
    years: "years",
    costBreakdown: "Cost Breakdown",
    taxType: "Tax/Fee Type",
    amount: "Amount",
    rate: "Rate",
    paidBy: "Paid By",
    buyer: "Buyer",
    seller: "Seller",
    split: "50/50",
    na: "N/A",
    summary: "Summary",
    buyerPays: "Buyer Pays",
    sellerPays: "Seller Pays",
    totalCosts: "Total Transfer Costs",
    incentiveApplied: "Government Incentive Applied",
    savings: "Savings",
    disclaimer: "Disclaimer",
    disclaimerText: "This report provides estimates based on standard Thai property transfer fees and taxes. Actual costs may vary depending on specific circumstances. The buyer/seller split shown is typical but negotiable. For accurate calculations specific to your transaction, please consult with a qualified legal professional.",
    poweredBy: "Powered by",
    fullCalculator: "Full Calculator",
    generatedBy: "Generated by Thailand Property Transfer Fee Calculator",
  },
  nl: {
    title: "Rapport Overdrachtskosten",
    subtitle: "Thailand Vastgoed Transactiekosten Analyse",
    reportDate: "Rapport Datum",
    reference: "Referentie",
    propertyDetails: "Vastgoed Gegevens",
    purchasePrice: "Aankoopprijs",
    registeredValue: "Kadastrale Waarde",
    yearsOwned: "Jaren in Bezit",
    sellerType: "Type Verkoper",
    mortgage: "Hypotheekbedrag",
    individual: "Particulier",
    company: "Bedrijf",
    years: "jaar",
    costBreakdown: "Kostenspecificatie",
    taxType: "Belasting/Kosten Type",
    amount: "Bedrag",
    rate: "Tarief",
    paidBy: "Betaald Door",
    buyer: "Koper",
    seller: "Verkoper",
    split: "50/50",
    na: "N.v.t.",
    summary: "Samenvatting",
    buyerPays: "Koper Betaalt",
    sellerPays: "Verkoper Betaalt",
    totalCosts: "Totale Overdrachtskosten",
    incentiveApplied: "Overheidsstimulans Toegepast",
    savings: "Besparing",
    disclaimer: "Disclaimer",
    disclaimerText: "Dit rapport geeft schattingen op basis van standaard Thaise vastgoed overdrachtskosten en belastingen. Werkelijke kosten kunnen afwijken afhankelijk van specifieke omstandigheden. De getoonde koper/verkoper verdeling is gebruikelijk maar onderhandelbaar. Raadpleeg voor nauwkeurige berekeningen een gekwalificeerde juridisch professional.",
    poweredBy: "Mogelijk gemaakt door",
    fullCalculator: "Volledige Calculator",
    generatedBy: "Gegenereerd door Thailand Property Transfer Fee Calculator",
  },
  it: {
    title: "Rapporto Spese di Trasferimento",
    subtitle: "Analisi Costi Transazione Immobiliare Thailandia",
    reportDate: "Data Rapporto",
    reference: "Riferimento",
    propertyDetails: "Dettagli Immobile",
    purchasePrice: "Prezzo di Acquisto",
    registeredValue: "Valore Catastale",
    yearsOwned: "Anni di Proprietà",
    sellerType: "Tipo Venditore",
    mortgage: "Importo Mutuo",
    individual: "Privato",
    company: "Azienda",
    years: "anni",
    costBreakdown: "Dettaglio Costi",
    taxType: "Tipo Tassa/Costo",
    amount: "Importo",
    rate: "Aliquota",
    paidBy: "Pagato Da",
    buyer: "Acquirente",
    seller: "Venditore",
    split: "50/50",
    na: "N/A",
    summary: "Riepilogo",
    buyerPays: "Acquirente Paga",
    sellerPays: "Venditore Paga",
    totalCosts: "Costi Totali Trasferimento",
    incentiveApplied: "Incentivo Governativo Applicato",
    savings: "Risparmio",
    disclaimer: "Disclaimer",
    disclaimerText: "Questo rapporto fornisce stime basate su tasse e imposte standard thailandesi. I costi effettivi possono variare. La divisione mostrata è tipica ma negoziabile. Per calcoli accurati consultare un professionista legale qualificato.",
    poweredBy: "Powered by",
    fullCalculator: "Calcolatore Completo",
    generatedBy: "Generato da Thailand Property Transfer Fee Calculator",
  },
  de: {
    title: "Übertragungsgebühren Bericht",
    subtitle: "Thailand Immobilien Transaktionskostenanalyse",
    reportDate: "Berichtsdatum",
    reference: "Referenz",
    propertyDetails: "Immobiliendetails",
    purchasePrice: "Kaufpreis",
    registeredValue: "Katasterwert",
    yearsOwned: "Jahre im Besitz",
    sellerType: "Verkäufertyp",
    mortgage: "Hypothekenbetrag",
    individual: "Privatperson",
    company: "Unternehmen",
    years: "Jahre",
    costBreakdown: "Kostenaufschlüsselung",
    taxType: "Steuer/Gebührenart",
    amount: "Betrag",
    rate: "Satz",
    paidBy: "Bezahlt von",
    buyer: "Käufer",
    seller: "Verkäufer",
    split: "50/50",
    na: "N/A",
    summary: "Zusammenfassung",
    buyerPays: "Käufer zahlt",
    sellerPays: "Verkäufer zahlt",
    totalCosts: "Gesamte Übertragungskosten",
    incentiveApplied: "Regierungsanreiz Angewendet",
    savings: "Ersparnis",
    disclaimer: "Haftungsausschluss",
    disclaimerText: "Dieser Bericht liefert Schätzungen basierend auf Standard-Übertragungsgebühren. Tatsächliche Kosten können variieren. Die gezeigte Aufteilung ist üblich aber verhandelbar. Für genaue Berechnungen konsultieren Sie einen Rechtsexperten.",
    poweredBy: "Bereitgestellt von",
    fullCalculator: "Vollständiger Rechner",
    generatedBy: "Erstellt mit Thailand Property Transfer Fee Calculator",
  },
  ru: {
    title: "Отчет о Расходах на Передачу",
    subtitle: "Анализ Затрат на Сделку с Недвижимостью в Таиланде",
    reportDate: "Дата Отчета",
    reference: "Номер",
    propertyDetails: "Данные Недвижимости",
    purchasePrice: "Цена Покупки",
    registeredValue: "Кадастровая Стоимость",
    yearsOwned: "Лет во Владении",
    sellerType: "Тип Продавца",
    mortgage: "Сумма Ипотеки",
    individual: "Физ. лицо",
    company: "Компания",
    years: "лет",
    costBreakdown: "Разбивка Расходов",
    taxType: "Тип Налога/Сбора",
    amount: "Сумма",
    rate: "Ставка",
    paidBy: "Оплачивает",
    buyer: "Покупатель",
    seller: "Продавец",
    split: "50/50",
    na: "Н/П",
    summary: "Итого",
    buyerPays: "Покупатель Платит",
    sellerPays: "Продавец Платит",
    totalCosts: "Общие Расходы",
    incentiveApplied: "Гос. Льгота Применена",
    savings: "Экономия",
    disclaimer: "Отказ от Ответственности",
    disclaimerText: "Этот отчет предоставляет оценки на основе стандартных тарифов. Фактические расходы могут отличаться. Распределение между сторонами типично, но может обсуждаться. Для точных расчетов проконсультируйтесь с юристом.",
    poweredBy: "При поддержке",
    fullCalculator: "Полный Калькулятор",
    generatedBy: "Создано Thailand Property Transfer Fee Calculator",
  },
  fr: {
    title: "Rapport des Frais de Transfert",
    subtitle: "Analyse des Coûts de Transaction Immobilière en Thaïlande",
    reportDate: "Date du Rapport",
    reference: "Référence",
    propertyDetails: "Détails du Bien",
    purchasePrice: "Prix d'Achat",
    registeredValue: "Valeur Cadastrale",
    yearsOwned: "Années de Propriété",
    sellerType: "Type de Vendeur",
    mortgage: "Montant du Prêt",
    individual: "Particulier",
    company: "Société",
    years: "ans",
    costBreakdown: "Détail des Coûts",
    taxType: "Type de Taxe/Frais",
    amount: "Montant",
    rate: "Taux",
    paidBy: "Payé Par",
    buyer: "Acheteur",
    seller: "Vendeur",
    split: "50/50",
    na: "N/A",
    summary: "Résumé",
    buyerPays: "L'Acheteur Paie",
    sellerPays: "Le Vendeur Paie",
    totalCosts: "Coûts Totaux de Transfert",
    incentiveApplied: "Incitation Gouvernementale Appliquée",
    savings: "Économie",
    disclaimer: "Avertissement",
    disclaimerText: "Ce rapport fournit des estimations basées sur les frais standards thaïlandais. Les coûts réels peuvent varier. La répartition acheteur/vendeur est typique mais négociable. Consultez un professionnel juridique pour des calculs précis.",
    poweredBy: "Propulsé par",
    fullCalculator: "Calculateur Complet",
    generatedBy: "Généré par Thailand Property Transfer Fee Calculator",
  },
  zh: {
    title: "房产过户费用报告",
    subtitle: "泰国房地产交易成本分析",
    reportDate: "报告日期",
    reference: "参考编号",
    propertyDetails: "房产详情",
    purchasePrice: "购买价格",
    registeredValue: "登记价值",
    yearsOwned: "持有年限",
    sellerType: "卖方类型",
    mortgage: "贷款金额",
    individual: "个人",
    company: "公司",
    years: "年",
    costBreakdown: "费用明细",
    taxType: "税费类型",
    amount: "金额",
    rate: "税率",
    paidBy: "支付方",
    buyer: "买方",
    seller: "卖方",
    split: "各50%",
    na: "不适用",
    summary: "汇总",
    buyerPays: "买方支付",
    sellerPays: "卖方支付",
    totalCosts: "总过户费用",
    incentiveApplied: "已应用政府优惠",
    savings: "节省",
    disclaimer: "免责声明",
    disclaimerText: "本报告基于泰国标准房产过户费用提供估算。实际费用可能因具体情况而异。买卖双方的分担比例是惯例但可协商。如需准确计算，请咨询法律专业人士。",
    poweredBy: "技术支持",
    fullCalculator: "完整计算器",
    generatedBy: "由泰国房产过户费用计算器生成",
  },
};

// ============================================
// HELPER FUNCTIONS
// ============================================

function generateReferenceNumber(): string {
  const now = new Date();
  const year = now.getFullYear();
  const month = String(now.getMonth() + 1).padStart(2, '0');
  const day = String(now.getDate()).padStart(2, '0');
  const random = Math.random().toString(36).substring(2, 6).toUpperCase();
  return `PTF-${year}${month}${day}-${random}`;
}

function formatDate(date: Date, lang: string): string {
  const options: Intl.DateTimeFormatOptions = { 
    year: 'numeric', 
    month: 'long', 
    day: 'numeric' 
  };
  
  const localeMap: Record<string, string> = {
    en: 'en-GB',
    nl: 'nl-NL',
    it: 'it-IT',
    de: 'de-DE',
    ru: 'ru-RU',
    fr: 'fr-FR',
    zh: 'zh-CN',
  };
  
  return date.toLocaleDateString(localeMap[lang] || 'en-GB', options);
}

function detectLanguage(t: TranslationStrings): string {
  // Detect language based on translation content
  if (t.propertyDetails === 'Vastgoed Details') return 'nl';
  if (t.propertyDetails === 'Dettagli Immobile') return 'it';
  if (t.propertyDetails === 'Immobiliendetails') return 'de';
  if (t.propertyDetails === 'Детали Недвижимости') return 'ru';
  if (t.propertyDetails === 'Détails du Bien') return 'fr';
  if (t.propertyDetails === '房产详情') return 'zh';
  return 'en';
}

// ============================================
// MAIN COMPONENT
// ============================================

export function PrintableReport({ 
  isOpen, 
  onClose, 
  result, 
  currency, 
  input,
  t 
}: PrintableReportProps) {
  const reportRef = useRef<HTMLDivElement>(null);
  
  const lang = detectLanguage(t);
  const rt = reportTranslations[lang as keyof typeof reportTranslations] || reportTranslations.en;
  
  const referenceNumber = generateReferenceNumber();
  const reportDate = formatDate(new Date(), lang);
  
  const handlePrint = () => {
    window.print();
  };
  
  return (
    <>
    <AnimatePresence>
      {isOpen && (
        <motion.div
          key="report-backdrop"
          initial={{ opacity: 0 }}
          animate={{ opacity: 1 }}
          exit={{ opacity: 0 }}
          className="fixed inset-0 bg-black/50 z-50 flex items-start justify-center p-4 overflow-y-auto print:bg-white print:p-0"
          onClick={onClose}
        >
          <motion.div
            key="report-modal"
            initial={{ scale: 0.95, opacity: 0 }}
            animate={{ scale: 1, opacity: 1 }}
            exit={{ scale: 0.95, opacity: 0 }}
            className="bg-white rounded-2xl shadow-2xl max-w-3xl w-full my-8 print:shadow-none print:rounded-none print:my-0 print:max-w-none"
            onClick={(e) => e.stopPropagation()}
          >
          {/* Controls - Hidden in print */}
          <div className="p-4 border-b border-gray-200 flex items-center justify-between print:hidden">
            <h3 className="font-semibold text-gray-900">
              {rt.title}
            </h3>
            
            <div className="flex items-center gap-2">
              <button
                onClick={handlePrint}
                className="flex items-center gap-2 px-4 py-2 bg-primary text-white rounded-lg font-medium hover:bg-primary/90 transition-colors"
              >
                <Icon icon="solar:printer-bold" className="w-5 h-5" />
                {t.print}
              </button>
              <button
                onClick={onClose}
                className="p-2 hover:bg-gray-100 rounded-lg"
              >
                <Icon icon="solar:close-circle-linear" className="w-5 h-5" />
              </button>
            </div>
          </div>
          
          {/* Report Content */}
          <div ref={reportRef} className="p-8 print:p-12" id="printable-report">
            {/* Header */}
            <div className="text-center mb-8 pb-6 border-b-2 border-gray-200">
              <h1 className="text-2xl font-bold text-gray-900 mb-1">
                {rt.title}
              </h1>
              <p className="text-gray-500 text-sm">
                {rt.subtitle}
              </p>
              
              <div className="flex flex-col sm:flex-row justify-center gap-2 sm:gap-8 mt-4 text-sm">
                <div>
                  <span className="text-gray-500">{rt.reportDate}:</span>{' '}
                  <span className="font-medium">{reportDate}</span>
                </div>
                <div>
                  <span className="text-gray-500">{rt.reference}:</span>{' '}
                  <span className="font-mono font-medium">{referenceNumber}</span>
                </div>
              </div>
            </div>
            
            {/* Property Details */}
            <div className="mb-8">
              <h2 className="text-lg font-semibold text-gray-900 mb-4 flex items-center gap-2">
                <span className="w-8 h-8 bg-blue-100 rounded-lg flex items-center justify-center">
                  <Icon icon="solar:home-2-linear" className="w-5 h-5 text-blue-600" />
                </span>
                {rt.propertyDetails}
              </h2>
              
              <div className="grid grid-cols-1 sm:grid-cols-2 gap-4 bg-gray-50 rounded-xl p-4">
                <div className="flex flex-col sm:flex-row sm:justify-between py-2 border-b border-gray-200 gap-1">
                  <span className="text-gray-600">{rt.purchasePrice}</span>
                  <span className="font-semibold">{formatCurrency(input.purchasePrice, currency)}</span>
                </div>
                <div className="flex flex-col sm:flex-row sm:justify-between py-2 border-b border-gray-200 gap-1">
                  <span className="text-gray-600">{rt.registeredValue}</span>
                  <span className="font-semibold">{formatCurrency(input.registeredValue, currency)}</span>
                </div>
                <div className="flex flex-col sm:flex-row sm:justify-between py-2 border-b border-gray-200 gap-1">
                  <span className="text-gray-600">{rt.yearsOwned}</span>
                  <span className="font-semibold">{input.yearsOwned} {rt.years}</span>
                </div>
                <div className="flex flex-col sm:flex-row sm:justify-between py-2 border-b border-gray-200 gap-1">
                  <span className="text-gray-600">{rt.sellerType}</span>
                  <span className="font-semibold">
                    {input.sellerType === 'individual' ? rt.individual : rt.company}
                  </span>
                </div>
                {(input.loanAmount ?? 0) > 0 && (
                  <div className="flex flex-col sm:flex-row sm:justify-between py-2 col-span-1 sm:col-span-2 gap-1">
                    <span className="text-gray-600">{rt.mortgage}</span>
                    <span className="font-semibold">{formatCurrency(input.loanAmount || 0, currency)}</span>
                  </div>
                )}
              </div>
            </div>
            
            {/* Cost Breakdown - Mobile Cards */}
            <div className="mb-8">
              <h2 className="text-lg font-semibold text-gray-900 mb-4 flex items-center gap-2">
                <span className="w-8 h-8 bg-purple-100 rounded-lg flex items-center justify-center">
                  <Icon icon="solar:chart-2-linear" className="w-5 h-5 text-purple-600" />
                </span>
                {rt.costBreakdown}
              </h2>
              
              {/* Mobile: Card Layout */}
              <div className="sm:hidden space-y-3">
                {Object.values(result.breakdown).map((item) => {
                  const translatedName = getTaxTypeName(item.name, t);
                  const paidByLabel = item.paidBy === 'buyer' ? rt.buyer 
                    : item.paidBy === 'seller' ? rt.seller 
                    : rt.split;
                  
                  return (
                    <div 
                      key={item.name}
                      className={cn(
                        "p-4 rounded-xl border border-gray-200 bg-white",
                        !item.isApplicable && "opacity-50"
                      )}
                    >
                      <div className="flex justify-between items-start mb-2">
                        <span className="font-medium text-gray-900">{translatedName}</span>
                        <span className={cn(
                          "px-2 py-0.5 rounded-full text-xs font-medium",
                          item.paidBy === 'buyer' && "bg-blue-100 text-blue-700",
                          item.paidBy === 'seller' && "bg-orange-100 text-orange-700",
                          item.paidBy === 'split' && "bg-purple-100 text-purple-700"
                        )}>
                          {paidByLabel}
                        </span>
                      </div>
                      <div className="flex justify-between items-baseline">
                        <span className="text-xl font-bold text-gray-900">
                          {item.isApplicable ? formatCurrency(item.amount, currency) : '—'}
                        </span>
                        <span className="text-sm text-gray-500">
                          {item.isApplicable ? item.rate : rt.na}
                        </span>
                      </div>
                    </div>
                  );
                })}
              </div>
              
              {/* Desktop: Table Layout */}
              <div className="hidden sm:block overflow-hidden rounded-xl border border-gray-200">
                <table className="w-full">
                  <thead>
                    <tr className="bg-gray-50">
                      <th className="text-left py-3 px-4 font-semibold text-gray-700 border-b border-gray-200">
                        {rt.taxType}
                      </th>
                      <th className="text-right py-3 px-4 font-semibold text-gray-700 border-b border-gray-200">
                        {rt.amount}
                      </th>
                      <th className="text-center py-3 px-4 font-semibold text-gray-700 border-b border-gray-200">
                        {rt.rate}
                      </th>
                      <th className="text-center py-3 px-4 font-semibold text-gray-700 border-b border-gray-200">
                        {rt.paidBy}
                      </th>
                    </tr>
                  </thead>
                  <tbody>
                    {Object.values(result.breakdown).map((item) => {
                      const translatedName = getTaxTypeName(item.name, t);
                      const paidByLabel = item.paidBy === 'buyer' ? rt.buyer 
                        : item.paidBy === 'seller' ? rt.seller 
                        : rt.split;
                      
                      return (
                        <tr 
                          key={item.name} 
                          className={cn(
                            "border-b border-gray-100",
                            !item.isApplicable && "text-gray-400"
                          )}
                        >
                          <td className="py-3 px-4">
                            {translatedName}
                          </td>
                          <td className="py-3 px-4 text-right font-semibold">
                            {item.isApplicable 
                              ? formatCurrency(item.amount, currency)
                              : '—'
                            }
                          </td>
                          <td className="py-3 px-4 text-center">
                            {item.isApplicable ? item.rate : rt.na}
                          </td>
                          <td className="py-3 px-4 text-center">
                            <span className={cn(
                              "px-2 py-1 rounded-full text-xs font-medium",
                              item.paidBy === 'buyer' && "bg-blue-100 text-blue-700",
                              item.paidBy === 'seller' && "bg-orange-100 text-orange-700",
                              item.paidBy === 'split' && "bg-purple-100 text-purple-700"
                            )}>
                              {paidByLabel}
                            </span>
                          </td>
                        </tr>
                      );
                    })}
                  </tbody>
                </table>
              </div>
            </div>
            
            {/* Summary */}
            <div className="mb-8">
              <h2 className="text-lg font-semibold text-gray-900 mb-4 flex items-center gap-2">
                <span className="w-8 h-8 bg-green-100 rounded-lg flex items-center justify-center">
                  <Icon icon="solar:calculator-linear" className="w-5 h-5 text-green-600" />
                </span>
                {rt.summary}
              </h2>
              
              <div className="bg-gradient-to-br from-gray-900 to-gray-800 rounded-xl p-6 text-white">
                <div className="grid grid-cols-2 gap-4 mb-4 pb-4 border-b border-gray-700">
                  <div>
                    <div className="text-blue-400 text-sm mb-1">{rt.buyerPays}</div>
                    <div className="text-2xl font-bold">
                      {formatCurrency(result.totals.buyerPays, currency)}
                    </div>
                  </div>
                  <div>
                    <div className="text-orange-400 text-sm mb-1">{rt.sellerPays}</div>
                    <div className="text-2xl font-bold">
                      {formatCurrency(result.totals.sellerPays, currency)}
                    </div>
                  </div>
                </div>
                
                <div className="flex justify-between items-center">
                  <div className="text-gray-400">{rt.totalCosts}</div>
                  <div className="text-3xl font-bold">
                    {formatCurrency(result.totals.grandTotal, currency)}
                  </div>
                </div>
                
                {result.incentiveSavings.qualifies && input.applyIncentive && (
                  <div className="mt-4 pt-4 border-t border-gray-700 flex items-center justify-between bg-green-900/30 -mx-6 -mb-6 px-6 py-4 rounded-b-xl">
                    <div className="flex items-center gap-2 text-green-400">
                      <Icon icon="solar:check-circle-bold" className="w-5 h-5" />
                      {rt.incentiveApplied}
                    </div>
                    <div className="text-green-400 font-semibold">
                      {rt.savings}: {formatCurrency(result.incentiveSavings.amountSaved, currency)}
                    </div>
                  </div>
                )}
              </div>
            </div>
            
            {/* Disclaimer */}
            <div className="mb-8 p-4 bg-amber-50 rounded-xl border border-amber-200">
              <h3 className="font-semibold text-amber-900 mb-2 flex items-center gap-2">
                <Icon icon="solar:info-circle-bold" className="w-5 h-5" />
                {rt.disclaimer}
              </h3>
              <p className="text-sm text-amber-800">
                {rt.disclaimerText}
              </p>
            </div>
            
            {/* Footer - Neutral, no branding */}
            <div className="pt-6 border-t border-gray-200 text-center text-sm text-gray-400">
              <p>{rt.generatedBy}</p>
            </div>
          </div>
          </motion.div>
        </motion.div>
      )}
    </AnimatePresence>
    
    {/* Print Styles - rendered when modal is open */}
    {isOpen && (
      <style dangerouslySetInnerHTML={{
        __html: `
          @media print {
            body * {
              visibility: hidden;
            }
            
            #printable-report,
            #printable-report * {
              visibility: visible;
            }
            
            #printable-report {
              position: absolute;
              left: 0;
              top: 0;
              width: 100%;
              padding: 40px !important;
            }
            
            .print\\:hidden {
              display: none !important;
            }
            
            @page {
              margin: 1cm;
              size: A4;
            }
          }
        `
      }} />
    )}
  </>
  );
}

export default PrintableReport;
